# docker-compose.dev.yml
# Development environment with PostgreSQL, MailHog, and Redis

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authdb_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    logging:
      driver: 'none' # Disable mailhog logging

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@postgres:5432/authdb_dev?sslmode=disable",
      "up"
    ]
    depends_on:
      postgres:
        condition: service_healthy

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Application
      APP_PORT: 8080
      APP_ENV: development
      # Database
      DB_DSN: postgres://postgres:postgres@postgres:5432/authdb_dev?sslmode=disable
      DB_MAX_OPEN_CONNS: 25
      DB_MAX_IDLE_CONNS: 5
      # JWT
      JWT_SECRET: dev-secret-key-for-testing-only
      JWT_ISSUER: go-auth-jwt
      JWT_ACCESS_TOKEN_TTL: 15m
      JWT_REFRESH_TOKEN_TTL: 168h
      JWT_ALGORITHM: HS256
      # Email
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: test@example.com
      SMTP_PASS: password
      EMAIL_FROM_ADDRESS: noreply@localhost
      EMAIL_FROM_NAME: Auth Service Dev
      EMAIL_WORKER_COUNT: 5
      EMAIL_QUEUE_SIZE: 100
      # Logging
      LOG_LEVEL: debug
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173,http://localhost:8080
      CORS_ALLOWED_METHODS: GET,POST,PUT,DELETE,OPTIONS
      CORS_ALLOWED_HEADERS: Authorization,Content-Type
      CORS_ALLOW_CREDENTIALS: true
      CORS_MAX_AGE: 3600
      RATE_LIMIT_ENABLED: false
      WORKER_POOL_SIZE: 2
      WORKER_QUEUE_SIZE: 10
      APP_BASE_URL: http://localhost:8080
      FRONTEND_URL: http://localhost:3000
    depends_on:
      migrate:
        condition: service_completed_successfully
      mailhog:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_dev_data:
  redis_dev_data: