apiVersion: v1
kind: ConfigMap
metadata:
  name: go-auth-jwt-config
data:
  # JWT Configuration
  JWT_ISSUER: "auth-service"
  JWT_ACCESS_TOKEN_DURATION: "15m"
  JWT_ALGORITHM: "HS256"
  
  # Email Configuration
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "noreply@yourdomain.com"
  SMTP_FROM_ADDRESS: "noreply@yourdomain.com"
  SMTP_FROM_NAME: "Auth Service"
  
  # Security Configuration
  CORS_ALLOWED_ORIGINS: "https://app.yourdomain.com,https://www.yourdomain.com"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "Authorization,Content-Type"
  CORS_ALLOW_CREDENTIALS: "true"
  CORS_MAX_AGE: "86400"
  
  # Rate Limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "60"
  RATE_LIMIT_BURST: "10"
  
  # Worker Pool
  WORKER_POOL_SIZE: "10"
  WORKER_QUEUE_SIZE: "100"
  
  # Application URLs
  APP_BASE_URL: "https://api.yourdomain.com"
  FRONTEND_URL: "https://app.yourdomain.com"
  
  # Database Configuration
  DATABASE_MAX_OPEN_CONNS: "25"
  DATABASE_MAX_IDLE_CONNS: "5"
  DATABASE_CONN_MAX_LIFETIME: "5m"
  DATABASE_CONN_MAX_IDLE_TIME: "1m"