apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-auth-jwt
  labels:
    app: go-auth-jwt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-auth-jwt
  template:
    metadata:
      labels:
        app: go-auth-jwt
    spec:
      containers:
        - name: api
          image: ghcr.io/n1rocket/go-auth-jwt:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PORT
              value: "8080"
            - name: ENVIRONMENT
              value: "production"
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: go-auth-jwt-secrets
                  key: database-dsn
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: go-auth-jwt-secrets
                  key: jwt-secret
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: go-auth-jwt-secrets
                  key: smtp-password
          envFrom:
            - configMapRef:
                name: go-auth-jwt-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: go-auth-jwt
  labels:
    app: go-auth-jwt
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: go-auth-jwt
