# This is a template for secrets. DO NOT commit actual secrets to version control!
# Use a secrets management solution like Kubernetes Secrets, AWS Secrets Manager, etc.
apiVersion: v1
kind: Secret
metadata:
  name: go-auth-jwt-secrets
type: Opaque
stringData:
  # Replace these with base64 encoded values in production
  database-dsn: "postgres://authuser:password@postgres-service:5432/authdb?sslmode=require"
  jwt-secret: "your-super-secret-key-minimum-32-characters-long"
  smtp-password: "your-smtp-password"